[package]
name = "jv-repo"
description = "Maven repository layout, metadata locations and checksum paths"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
jv-model = { workspace = true }
jv-version = { workspace = true }

[lints]
workspace = true
